<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <VersionPrefix>0.6.5</VersionPrefix>

    <Title>Sylvan Json Resource</Title>
    <Summary>Sylvan Json Resource provides a Json based alternative to resx resource files.</Summary>
    <Description>Json Resource File</Description>
    <PackageTags>resj;resource;json</PackageTags>

    <NoPackageAnalysis>true</NoPackageAnalysis>
    <BuildOutputTargetFolder>build</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PackageTags>resj resource json</PackageTags>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>

    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1903</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="build\*" PackagePath="build\">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <None
      Condition="Exists($(ReadmeFile))"
      Include="$(ReadmeFile)"
      Pack="true"
      PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="18.3.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.3.3" PrivateAssets="all" />
    <PackageReference Include="Sylvan.Json" Version="0.1.1" PrivateAssets="all" />
    <PackageReference Update="Microsoft.Build.Tasks.Git" Version="10.0.103" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.103" />
  </ItemGroup>

</Project>
